<a href="https://colab.research.google.com/github/nsalazard/Introduction_To_Cryptography/blob/main/TurningGrille/TurningGrille.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def CreateGrill(matrix, indices):
    pairs = indices.split()
    for pair in pairs:
        row, col = map(int, pair.split(','))
        if 0 <= row < len(matrix) and 0 <= col < len(matrix[0]):
            matrix[row][col] = 1
        else:
            print(f"Error: Los indices estan fuera de los limites")
    return matrix

def ValidateGrill(matrix, size):
  matrix_copy = matrix.copy()
  result = np.zeros((size, size))
  for i in range(size):
    result += matrix_copy
    matrix_copy = np.rot90(matrix_copy)
  if size%2 == 1 and result[size//2, size//2] > 1:
    result[size//2, size//2] = 1
  if np.all(result == 1):
    return True
  else:
    return False

def encrypt_message(message, grille, size, DRot):

    message = message.upper().replace(" ", "")
    message_length = len(message)
    encrypted_message = ""
    matrix = np.empty((size, size), dtype=str)
    matrix[:] = ''

    #grille_positions = []
    aux = 1 if DRot == 0 else -1

    if size%2 == 1:
      middle =  message[len(message)//2]
      grille[size//2, size//2] = 0

    current_index = 0
    for rotation in range(4):
        for i in range(size):
          for j in range(size):
            if current_index < message_length:
                if size%2 == 1 and rotation == 0 and (i == size //2 and j == size//2):
                  matrix[i, j] = message[current_index]
                  current_index += 1
                elif grille[i, j] == 1:
                  matrix[i, j] = message[current_index]
                  current_index += 1
                  #grille_positions.append((i,j))
                  #print(matrix)
                  #print('----------------------------')

        grille =  np.rot90(grille, k = aux, axes=(0,1))

    for i in range(size):
        for j in range(size):
            if matrix[i,j] != '':
                encrypted_message += matrix[i,j]

    return encrypted_message

def decrypt_message(encrypted_message, grille, size, DRot):

    aux = 1 if DRot == 0 else -1
    grille = np.rot90(grille, k = aux, axes=(0,1))

    decrypted_message = ""
    decrypted_array = []
    message_length = len(encrypted_message)
    matrix = np.empty((size, size), dtype=str)
    matrix[:] = ''
    index_message = 0
    for i in range(size):
            for j in range(size):
              matrix[i,j] = encrypted_message[index_message]
              index_message += 1

    flag = 0
    for rotation in range(4):
      ii = 0
      if size%2 == 1:
        grille[size //2, size //2] = 0
      for i in range(size):
        for j in range(size):
          if rotation == 3 and (i == size //2 and j == size//2) and size%2 == 1:
            decrypted_array.insert(ii, matrix[size //2,size //2])
            ii += 1

          elif grille[i, j] == 1:
            decrypted_array.insert(ii, matrix[i,j])
            ii += 1
      grille = np.rot90(grille, k = aux, axes=(0,1))

    decrypted_message = ''.join(decrypted_array)
    return decrypted_message

def main():

  size = int(input("Ingresa el tamano de la reticula: "))
  matrix = np.zeros((size, size))
  total_size = size*size
  modo = int(input("Para cifrar ingresar 0 y para decifrar 1: "))
  DRot = int(input("Ingresar direccion de rotacion (sentido de las manecillas del reloj o sentido contrario, 1 o 0 respectivamente): "))

  indices = input("Ingresar los indices ")
  grill = CreateGrill(matrix, indices)
  print(ValidateGrill(grill, size))
  for row in grill:
    print(row)

  message = input("Enter the message: ")
  message = message.replace(" ", "")

  if len(message) % total_size != 0:
    padding = total_size - (len(message) % total_size)
    message += "X" * padding

  if modo == 0:
    encrypted_message = ''
    for i in range(0, len(message), total_size):
      new_message = message[i:i+total_size]
      encrypted_message += encrypt_message(new_message, grill, size, DRot)
    print("Encrypted message:", encrypted_message)
  elif modo == 1:
    decrypted_message = ''
    for i in range(0, len(message), total_size):
        new_message = message[i:i+total_size]
        decrypted_message += decrypt_message(new_message, grill, size, DRot)
    print("Decrypted message:", decrypted_message)

if __name__ == "__main__":
    main()
# 0,0 2,1 2,3 3,2
#JIM ATTACKS AT DAWN AND THEN RUN

Ingresa el tamano de la reticula: 9
Para cifrar ingresar 0 y para decifrar 1: 1
Ingresar direccion de rotacion (sentido de las manecillas del reloj o sentido contrario, 1 o 0 respectivamente): 1
Ingresar los indices 0,0 0,3 0,5 1,2 1,8 2,1 2,6 3,2 3,4 3,7 4,4 4,6 4,8 5,3 5,7 6,0 6,5 7,1 7,4 7,8 8,2
False
[1. 0. 0. 1. 0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 1.]
[0. 1. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 1. 0. 0. 1. 0.]
[0. 0. 0. 0. 1. 0. 1. 0. 1.]
[0. 0. 0. 1. 0. 0. 0. 1. 0.]
[1. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 1. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0. 0.]
Enter the message: TESHNINCIGLSRGYLRIUSPITSATLILMREENSATTOGSIAWGIPVERTOTEHHVAEAXITDTUAIMERANPMTLHIEI
Decrypted message: THISISAMESSAGETHATIAMENCRYPTINGWITHATURNINGGRILLETOPROVIDETHISILLUSTRATIVEEXAMPLE


In [ ]:
#THISISAMESSAGETHATIAMENCRYPTINGWITHATURNINGGRILLETOPROVIDETHISILLUSTRATIVEEXAMPLE
#0,0 0,3 0,5 1,2 1,8 2,1 2,6 3,2 3,4 3,7 4,4 4,6 4,8 5,3 5,7 6,0 6,5 7,1 7,4 7,8 8,2
#TESHN INCIG LSRGY LRIUS PITSA TLILM REENS ATTOG SIAWG IPVER TOTEH HVAEA XITDT UAIME RANPM TLHIE I

#TESHNINCIGLSRGYLRIUSPITSATLILMREENSATTOGSIAWGIPVERTOTEHHVAEAXITDTUAIMERANPMTLHIEI